{{cookiecutter.project_name}}/api/urls.py
from django.conf.urls import url, include
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    # Error handling
    url(r'^v1/', include('api.v1.urls')),

]

{{cookiecutter.project_name}}/blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _
from . import views

urlpatterns = [
    # Error handling
    url(_(r'^$'), views.posts, name='posts'),
    url(_(r'^/categories/(?P<category_slug>[a-zA-Z0-9_-]+)$'), views.category, name='category'),
    url(_(r'^/articles/(?P<article_slug>[a-zA-Z0-9_-]+)$'), views.article, name='article'),
]

# 

{{cookiecutter.project_name}}/front/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _
from . import views


urlpatterns = [
    # Error handling
    url(r'^404$', views.handler404, name='404'),
    url(r'^500$', views.handler500, name='500'),

    # Static pages
    url(r'^$', views.home, name='home'),
]

{{cookiecutter.project_name}}/main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib.sitemaps.views import sitemap

# Sitemaps example
# from .sitemaps import PageSiteMap, BlogSiteMap

# sitemaps = {'sitemaps':
#             {'projects': PageSiteMap,
#             'articles':BlogSiteMap,
#              }
sitemaps = {'sitemap': {}}


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^redactor/', include('redactor.urls')),
    {% if cookiecutter.api % }
    url(r'^api/', include('api.urls')),
    {% endif % }
    url(r'^mails/', include('mails.urls', namespace='mails')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^sitemap\.xml$', sitemap, sitemaps, name='django.contrib.sitemaps.views.sitemap'),


]


urlpatterns += i18n_patterns(
    url(r'^', include('front.urls', namespace='front')),
    { % if cookiecutter.blog % } url(r'^{{ cookiecutter.blog_url }}', include('blog.urls', namespace='blog')), { % endif % }
    { % if cookiecutter.faq % } url(r'^{{ cookiecutter.faq_url }}', include('faq.urls', namespace='faq')), { % endif % }

)

handler404 = 'front.views.error404'
handler500 = 'front.views.error500'

{{cookiecutter.project_name}}/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils import timezone
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify

# Create your models here.
from django.utils.html import format_html

STATES = [
    (0, _(u"Draft")),
    (1, _(u"Published"))
]


class Category(models.Model):
    """
    Define a category for a Blog post

    Available template tag: 
    category_badge category  will return "badge stuff"


    ##TODO: 
    -Need to build our own custom widget for colorfield (based on a library right now)
    -Need to create a relevant Icon class to allow icon selection (from another app?)
    """

    name = models.CharField(verbose_name=_(u"Nom"), max_length=200)

    slug = models.SlugField(_(u"Adresse"), unique=True, editable=False, default=None)
    order = models.IntegerField(_(u"Ordre d'apparition"))
    description = models.TextField(_(u"Meta description"), help_text=_(u"Description (pour référencement)"))

    created_at = models.DateTimeField(verbose_name=_(u"Création"), auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name=_(u"Mise à jour"), auto_now=True)

    class Meta:
        verbose_name = _(u"Categorie d'une actualié")
        verbose_name_plural = _(u"Categories des actualités")
        ordering = ['order']

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        for child in self.__class__.objects.filter(order=self.order).exclude(id=self.id):
            child.order += 1
            child.save()
        if self.slug is None:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    @property
    def colored_name(self):
        """
        return colored label
        """
        return format_html('<span style="background-color:%s;">%s</span>' % (self.bg_color, self.name))


class PostManager(models.Manager):
    """
    Manager for post model
    """

    def published(self):
        return self.filter(state=1)

    def current(self):
        return self.published().order_by("-published_at")


class Post(models.Model):
    """
    Define a Blog (news)
    """
    category = models.ForeignKey('blog.Category', related_name='posts')

    title = models.CharField(_(u"Titre"), max_length=90, unique=True)
    subtitle = models.CharField(_(u"Titre second niveau"), max_length=150)
    slug = models.SlugField(_(u"Adresse"), unique=True, editable=False, default=None)

    short_content = models.CharField(_(u"Résumé"), max_length=300)
    content = models.TextField(_(u"Contenu"))
    description = models.TextField(_(u"Meta description"), help_text=_(u"Description (pour référencement)"))

    created_at = models.DateTimeField(verbose_name=_(u"Création"), auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name=_(u"Mise à jour"), auto_now=True)
    published_at = models.DateTimeField(_(u"Publication"),
                                        null=True, blank=True)
    state = models.SmallIntegerField(_(u"Publication"), choices=STATES)

    # image_upload = models.ManyToManyField('images.Image', verbose_name=_(u"Photo de l'article"), related_name='posts')
    cover = models.ForeignKey('images.Image', verbose_name=_(
        u"Image Vignette"), related_name='cover', blank=True, null=True)
    picture = models.ForeignKey('images.Image', verbose_name=_(u"Image Article"), related_name='posts')

    related_articles = models.ManyToManyField(
        'blog.Post', verbose_name=_(u"Artciles associés"), related_name='referenced_articles', blank=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _(u"Actualié")
        verbose_name_plural = _(u"Actualités")
        ordering = ['-published_at']

    def save(self, *args, **kwargs):
        """
        Update published_at
        """
        if self.is_published and self.published_at is None:
            self.published_at = timezone.now()

        if self.slug is None:
            self.slug = slugify(self.title)

        super(Post, self).save(*args, **kwargs)

    @property
    def is_published(self):
        return self.state == 1

    @property
    def suggestions(self):
        return self.related_articles.filter(state=1)

{{cookiecutter.project_name}}/blog/forms.py
from django.forms import ModelForm
from django.contrib.admin import ModelAdmin

from redactor.widgets import RedactorEditor

from .models import Category, Post


class PostContentForm(ModelForm):
    """
    Form used in admin
    """
    class Meta:
        model = Post
        fields = '__all__'
        widgets = {
            'content': RedactorEditor()
        }



class CategoryForm(ModelForm):
    pass
    # class Meta:
    #     model = Category
    #     fields = '__all__'
    #     widgets = {
    #         'bg_color': HTML5Input(input_type='color'),
    #         'font_color': HTML5Input(input_type='color'),
    #     }

{{cookiecutter.project_name}}/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import (
    render,
    get_object_or_404,
    get_list_or_404)
from django.utils.translation import ugettext_lazy as _
from django.db.models import Count

from .models import Post, Category
# Create your views here.


def posts(request):
    title = _(u"Journal - MyWine")
    posts = Post.objects.filter(state=1)
    categories = Category.objects.annotate(count_posts=Count('posts')).filter(count_posts__gt=0)
    return render(request, 'blog/news.html',
                  {'title': title,
                   'posts': posts,
                   'categories': categories
                   })


def category(request, category_slug):
    title = _(u"Journal - Catégorie")

    categories = Category.objects.annotate(count_posts=Count('posts')).filter(count_posts__gt=0)
    posts = get_list_or_404(Post, category__slug=category_slug, state=1)
    return render(request, 'blog/news.html',
                  {'title': title,
                   'posts': posts,
                   'categories': categories
                   })


def article(request, article_slug):
    title = _(u"Journal - Catégorie")

    categories = Category.objects.annotate(count_posts=Count('posts')).filter(count_posts__gt=0)
    post = get_object_or_404(Post, slug=article_slug, state=1)
    related_posts = post.related_articles.filter(state=1)[:2]
    
    return render(request, 'blog/post.html',
                  {'title': title,
                   'post': post,
                   'categories': categories,
                   'related_posts':related_posts
                   })

{{cookiecutter.project_name}}/blog/templates/blog/news.html
{% raw %}
{% extends 'front/_layout.html' %}

{% load staticfiles blog_ui %}

{% block title %}{{ title }}{% endblock %}

{% block meta %}
    <meta name="description" content="" />
    <meta name="keywords" content="" /> 
    <meta property="og:title" content="" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:description" content="" />
    <meta name="twitter:image" content="" />
{% endblock %}
{% block body %}news{% endblock body %}

{% block main %}
<section class="blk-title">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <ol class="breadcrumb">
                    <li><a href="{% url 'front:home' %}">Accueil</a></li>
                    <li class="active">Actualités</li>
                </ol>       
            </div>
            <div class="col-sm-4">
                <h1 class="text-center text-gray text-uppercase">les actus d'ipi</h1>
            </div>
            <div class="col-sm-4">
                <div class="btn-group">
                    <button type="button" class="btn btn-gray btn-radius dropdown-toggle ff1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Toutes les catégories <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        {% for category in categories  %}
                            <li><a href="{% url 'blog:category' category.slug %}">{{ category.name }}</a></li>    
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="bg-gray pvm">
    <div class="container">
        {% for post in posts %}
            {% render_post post %}
        {% endfor %}
    </div>
</section>
{% endblock main %}
{% endraw %}

{{cookiecutter.project_name}}/blog/templates/blog/post.html
{% raw %}
{% extends 'front/_layout.html' %}
{% load static blog_ui %}

{% block head %}
    <title> {{title}} </title>
    <meta name="description" content="Page description. No longer than 155 characters." />

    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="The Name or Title Here">
    <meta itemprop="description" content="This is the page description">
    <meta itemprop="image" content="http://www.example.com/image.jpg">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@publisher_handle">
    <meta name="twitter:title" content="Page Title">
    <meta name="twitter:description" content="Page description less than 200 characters">
    <meta name="twitter:creator" content="@author_handle">
    <!-- Twitter summary card with large image must be at least 280x150px -->
    <meta name="twitter:image:src" content="http://www.example.com/image.html">

    <!-- Open Graph data -->
    <meta property="og:title" content="Title Here" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="http://www.example.com/" />
    <meta property="og:image" content="http://example.com/image.jpg" />
    <meta property="og:description" content="Description Here" />
    <meta property="og:site_name" content="Site Name, i.e. Moz" />
    <meta property="article:published_time" content="2013-09-17T05:59:00+01:00" />
    <meta property="article:modified_time" content="2013-09-16T19:08:47+01:00" />
    <meta property="article:section" content="Article Section" />
    <meta property="article:tag" content="Article Tag" />
    <meta property="fb:admins" content="Facebook numberic ID" />
{% endblock head %}  


{% block main %}
<section class="bg-gray-lighter">
    <div class="container pvl position-relative">
        <a class="previous-article" href=""><i class="icon-blog-arrow-left"></i></a>
        <a class="next-article" href=""><i class="icon-blog-arrow-right"></i></a>
        <p class="text-center text-electric text-space-lg small mbx">01.02.15</p>
        <div class="row">
            <div class="col-sm-offset-2 col-sm-8 pan">
                <div class="bg-image image-block" style="background-image: url({% static 'clubvin/img/bg-image-home.png' %});"></div>           
            </div>
        </div>
        <div class="row">
            <div class="col-sm-offset-2 col-sm-8 article-content pas">
                <div class="bg-white pam">
                    <h1 class="mtn header-lg">{{ post.title|upper }}</h1>
                    <p class="text-electric">{{ post.subtitle }}</p>
                    <hr class="mvs">
                    {{ post.content|safe }}
                </div>              
            </div>
            <div class="col-sm-offset-2 col-sm-8 mtx">
                <div class="bg-white phs pbs ptx">
                    <h3 class="mtn small sans-serif text-center text-uppercase text-space">bientôt dans vos caves</h3>
                    <hr class="man">
                    <div class="row mtx">
                        {% for a in 'abc' %}
                        <div class="col-sm-4 text-center">
                            {% include 'front/elements/_bottle.html' %}
                        </div>
                        {% endfor %}
                    </div>
                </div>              
            </div>
            <div class="col-sm-offset-2 col-sm-8 mtx">
                <div class="row">
                    <div class="diary-block">
                        {% for related in related_posts %}
                            {% render_post related %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
    
{% endblock main %}
{% endraw %}